server:
  port: 8090

spring:
  cloud:
    discovery.client.simple.instances:
      books:
        - uri: http://localhost:8091/books
      movies:
        - uri: http://localhost:8091/movies

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  timelimiter:
    instances:
      books:
        timeoutDuration: 2s
        cancelRunningFuture: true
  retry:
    instances:
      movies:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2